
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package org.apache.cxf.huge64.ws;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.InputStream;
import java.util.logging.Logger;

import javax.activation.DataHandler;

import org.apache.cxf.huge64.data.UploadStatus;

/**
 * This class was generated by Apache CXF 2.7.5
 * 2015-05-15T17:55:25.391-03:00
 * Generated source version: 2.7.5
 * 
 */

@javax.jws.WebService(
                      serviceName = "huge64Service",
                      portName = "huge64Port",
                      targetNamespace = "http://www.example.org/huge64",
                      wsdlLocation = "huge64.wsdl",
                      endpointInterface = "org.apache.cxf.huge64.ws.Huge64PortType")
                      
public class Huge64PortTypeImpl implements Huge64PortType {

    private static final Logger LOG = Logger.getLogger(Huge64PortTypeImpl.class.getName());

    /* (non-Javadoc)
     * @see org.apache.cxf.huge64.ws.Huge64PortType#sendHugeFile(org.apache.cxf.huge64.data.HugeFile  sendHugeFileRequestPart )*
     */
    public org.apache.cxf.huge64.data.UploadStatus sendHugeFile(org.apache.cxf.huge64.data.HugeFile sendHugeFileRequestPart) { 
        LOG.info("Executing operation sendHugeFile");
        System.out.println(sendHugeFileRequestPart);
        try {
        	
        	DataHandler dataHandler = sendHugeFileRequestPart.getXml();
        	int size = dataHandler.getInputStream().available();
        	ByteArrayOutputStream os = new ByteArrayOutputStream(size);
        	dataHandler.writeTo(os);
        	
        	System.out.println(new String(os.toByteArray()));
        	
            UploadStatus _return = new UploadStatus();
            _return.setStatus("OK");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
