package org.apache.cxf.huge64.ws;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.5
 * 2015-05-15T17:55:25.420-03:00
 * Generated source version: 2.7.5
 * 
 */
@WebServiceClient(name = "huge64Service", 
                  wsdlLocation = "huge64.wsdl",
                  targetNamespace = "http://www.example.org/huge64") 
public class Huge64Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.example.org/huge64", "huge64Service");
    public final static QName Huge64Port = new QName("http://www.example.org/huge64", "huge64Port");
    static {
        URL url = Huge64Service.class.getResource("ws/huge64.wsdl");
        if (url == null) {
            url = Huge64Service.class.getClassLoader().getResource("ws/huge64.wsdl");
        } 
        if (url == null) {
            java.util.logging.Logger.getLogger(Huge64Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "huge64.wsdl");
        }       
        WSDL_LOCATION = url;
    }

    public Huge64Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public Huge64Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Huge64Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns Huge64PortType
     */
    @WebEndpoint(name = "huge64Port")
    public Huge64PortType getHuge64Port() {
        return super.getPort(Huge64Port, Huge64PortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Huge64PortType
     */
    @WebEndpoint(name = "huge64Port")
    public Huge64PortType getHuge64Port(WebServiceFeature... features) {
        return super.getPort(Huge64Port, Huge64PortType.class, features);
    }

}
