package org.apache.cxf.huge64.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.5
 * 2015-05-15T17:55:25.405-03:00
 * Generated source version: 2.7.5
 * 
 */
@WebService(targetNamespace = "http://www.example.org/huge64", name = "huge64PortType")
@XmlSeeAlso({ObjectFactory.class, org.apache.cxf.huge64.data.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface Huge64PortType {

    @WebResult(name = "SendHugeFileResponse", targetNamespace = "http://www.example.org/huge64", partName = "sendHugeFileResponsePart")
    @WebMethod(action = "http://www.example.org/huge64/sendHugeFile")
    public org.apache.cxf.huge64.data.UploadStatus sendHugeFile(
        @WebParam(partName = "sendHugeFileRequestPart", name = "SendHugeFileRequest", targetNamespace = "http://www.example.org/huge64")
        org.apache.cxf.huge64.data.HugeFile sendHugeFileRequestPart
    );
}
