
package org.apache.cxf.huge64.ws;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 2.7.5
 * 2015-05-15T17:55:25.368-03:00
 * Generated source version: 2.7.5
 * 
 */
public final class Huge64PortType_Huge64Port_Client {

    private static final QName SERVICE_NAME = new QName("http://www.example.org/huge64", "huge64Service");

    private Huge64PortType_Huge64Port_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = Huge64Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        Huge64Service ss = new Huge64Service(wsdlURL, SERVICE_NAME);
        Huge64PortType port = ss.getHuge64Port();  
        
        {
        System.out.println("Invoking sendHugeFile...");
        org.apache.cxf.huge64.data.HugeFile _sendHugeFile_sendHugeFileRequestPart = null;
        org.apache.cxf.huge64.data.UploadStatus _sendHugeFile__return = port.sendHugeFile(_sendHugeFile_sendHugeFileRequestPart);
        System.out.println("sendHugeFile.result=" + _sendHugeFile__return);


        }

        System.exit(0);
    }

}
