
package org.apache.cxf.huge64.ws;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.7.5
 * 2015-05-15T17:55:25.414-03:00
 * Generated source version: 2.7.5
 * 
 */
 
public class Huge64PortType_Huge64Port_Server{

    protected Huge64PortType_Huge64Port_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new Huge64PortTypeImpl();
        String address = "http://localhost:8080/huge64/cxf/sendHugeFile";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new Huge64PortType_Huge64Port_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
